// Tables Column
// super Admin
export const usersSuperAdminTablesColumn = [
  {
    label: "SNo",
    field: "S.No",
    icon: false,
    deleteIcon: false,
    editIcon: false,
    image: false,
    switchbtn: false,
    statusbtn: false,
    width: 100,
  },
  {
    label: "User_Name",
    field: "User Name",
    icon: false,
    deleteIcon: false,
    editIcon: false,
    image: true,
    switchbtn: false,
    statusbtn: false,
    width: 300,
  },
  {
    label: "Contact",
    field: "Contact",
    icon: false,
    deleteIcon: false,
    editIcon: false,
    image: false,
    switchbtn: false,
    statusbtn: false,
    width: 200,
  },
  {
    label: "Institute_user",
    field: "Institute user",
    icon: false,
    deleteIcon: false,
    editIcon: false,
    image: false,
    switchbtn: false,
    statusbtn: false,
    width: 300,
  },
  {
    label: "Email",
    field: "Email",
    icon: false,
    deleteIcon: false,
    editIcon: false,
    image: false,
    switchbtn: false,
    statusbtn: false,
    width: 300,
  },
  {
    label: "Account_created_on",
    field: "Account created on",
    icon: false,
    deleteIcon: false,
    editIcon: false,
    image: false,
    switchbtn: false,
    statusbtn: false,
    width: 200,
  },
  {
    label: "Last_Login",
    field: "Last Login",
    icon: false,
    deleteIcon: false,
    editIcon: false,
    image: false,
    switchbtn: false,
    statusbtn: false,
    width: 200,
  },
  {
    label: "Status",
    field: "Status",
    icon: false,
    deleteIcon: false,
    editIcon: false,
    image: false,
    switchbtn: false,
    statusbtn: true,
    width: 200,
  },
  {
    label: "Deactivate",
    field: "Deactivate",
    icon: false,
    deleteIcon: false,
    editIcon: false,
    image: false,
    switchbtn: true,
    statusbtn: false,
    width: 200,
  },
  {
    label: "Take_Actions",
    field: "Take Actions",
    icon: true,
    deleteIcon: false,
    editIcon: true,
    image: false,
    switchbtn: false,
    statusbtn: false,
    subScrIcon: true,
    width: 150,
  },
];

export const ebooksTablesColumn = [
  {
    label: "SNo",
    field: "S.No",
    icon: false,
    deleteIcon: false,
    editIcon: false,
    image: false,
    switchbtn: false,
    statusbtn: false,
  },
  {
    label: "E_book_Name",
    field: "E_book_Name",
    icon: false,
    deleteIcon: false,
    editIcon: false,
    image: true,
    switchbtn: false,
    statusbtn: false,
  },
  {
    label: "Category",
    field: "Category",
    icon: false,
    deleteIcon: false,
    editIcon: false,
    image: false,
    switchbtn: false,
    statusbtn: false,
  },
  {
    label: "Author",
    field: "Author",
    icon: false,
    deleteIcon: false,
    editIcon: false,
    image: false,
    switchbtn: false,
    statusbtn: false,
  },
  {
    label: "Type",
    field: "Type",
    icon: false,
    deleteIcon: false,
    editIcon: false,
    image: false,
    switchbtn: false,
    statusbtn: false,
  },

  {
    label: "Take_Actions",
    field: "Take Actions",
    icon: true,
    deleteIcon: true,
    editIcon: true,
    image: false,
    switchbtn: false,
    statusbtn: false,
    subScrIcon: false,
  },
];

export const InstitutesTablesColumn = [
  {
    label: "SNo",
    field: "S.No",
    icon: false,
    deleteIcon: false,
    editIcon: false,
    image: false,
    switchbtn: false,
    statusbtn: false,
  },
  {
    label: "Institute_Name",
    field: "Institute Name",
    icon: false,
    deleteIcon: false,
    editIcon: false,
    image: true,
    switchbtn: false,
    statusbtn: false,
  },
  {
    label: "Contact",
    field: "Contact",
    icon: false,
    deleteIcon: false,
    editIcon: false,
    image: false,
    switchbtn: false,
    statusbtn: false,
  },

  {
    label: "Email",
    field: "Email",
    icon: false,
    deleteIcon: false,
    editIcon: false,
    image: false,
    switchbtn: false,
    statusbtn: false,
  },
  {
    label: "Account_created_on",
    field: "Account created on",
    icon: false,
    deleteIcon: false,
    editIcon: false,
    image: false,
    switchbtn: false,
    statusbtn: false,
  },

  {
    label: "Status",
    field: "Status",
    icon: false,
    deleteIcon: false,
    editIcon: false,
    image: false,
    switchbtn: false,
    statusbtn: true,
  },
  {
    label: "Total_users",
    field: "Total users",
    icon: false,
    deleteIcon: false,
    editIcon: false,
    image: false,
    switchbtn: false,
    statusbtn: true,
  },
  {
    label: "Deactivate",
    field: "Deactivate",
    icon: false,
    deleteIcon: false,
    editIcon: false,
    image: false,
    switchbtn: true,
    statusbtn: false,
  },
  {
    label: "Take_Actions",
    field: "Take Actions",
    icon: true,
    deleteIcon: false,
    editIcon: true,
    image: false,
    switchbtn: false,
    statusbtn: false,
    subScrIcon: true,
  },
];

// subscription table column
export const SubscriptionTablesColumn = [
  {
    label: "SNo",
    field: "S.No",
    icon: false,
    deleteIcon: false,
    editIcon: false,
    image: false,
    switchbtn: false,
    statusbtn: false,
  },
  {
    label: "Subscription Name",
    field: "Subscription_Name",
    icon: false,
    deleteIcon: false,
    editIcon: false,
    image: false,
    switchbtn: false,
    statusbtn: false,
  },
  {
    label: "Features",
    field: "Features",
    icon: false,
    deleteIcon: false,
    editIcon: false,
    image: false,
    switchbtn: false,
    statusbtn: false,
  },
  {
    label: "Rate",
    field: "Rate",
    icon: false,
    deleteIcon: false,
    editIcon: false,
    image: false,
    switchbtn: false,
    statusbtn: false,
  },
  {
    label: "Duration",
    field: "Duration",
    icon: false,
    deleteIcon: false,
    editIcon: false,
    image: false,
    switchbtn: false,
    statusbtn: false,
  },

  {
    label: "Take_Actions",
    field: "Take Actions",
    icon: true,
    deleteIcon: true,
    editIcon: true,
    image: false,
    switchbtn: false,
    statusbtn: false,
    subScrIcon: true,
  },
];

// Quiz table column
export const QuizTablesColumn = [
  {
    label: "SNo",
    field: "S.No",
    icon: false,
    deleteIcon: false,
    editIcon: false,
    image: false,
    switchbtn: false,
    statusbtn: false,
  },
  {
    label: "Quiz_Name",
    field: "Quiz_Name",
    icon: false,
    deleteIcon: false,
    editIcon: false,
    image: false,
    switchbtn: false,
    statusbtn: false,
  },
  {
    label: "No Of questIon",
    field: "No_Of_questIon",
    icon: false,
    deleteIcon: false,
    editIcon: false,
    image: false,
    switchbtn: false,
    statusbtn: false,
  },
  {
    label: "Solved_by_No_of_users",
    field: "Solved_by_No_of_users",
    icon: false,
    deleteIcon: false,
    editIcon: false,
    image: false,
    switchbtn: false,
    statusbtn: false,
  },

  {
    label: "Take_Actions",
    field: "Take Actions",
    icon: true,
    deleteIcon: true,
    editIcon: false,
    image: false,
    switchbtn: false,
    statusbtn: false,
    subScrIcon: false,
  },
];

// Institute Admin
const usersTablesColumn = [
  { label: "S.No", field: "S.No", icon: false, image: false },
  { label: "User Name", field: "User Name", icon: false, image: true },
  { label: "Contact", field: "Contact", icon: false, image: false },
  {
    label: "Email",
    field: "Email",
    icon: false,
    image: false,
  },

  {
    label: "Account created on",
    field: "Account created on",
    icon: false,
    image: false,
  },
  {
    label: "Current Subscription Plan",
    field: "Current Subscription Plan",
    icon: false,
    image: false,
  },
  { label: "Status", field: "Status", icon: false, image: false },
  { label: "Deactivate", field: "Deactivate", icon: false, image: false },
  { label: "Take Actions", field: "Take Actions", icon: true, image: false },
];
