// Tables Column
// super Admin
export const usersSuperAdminTablesColumn = [
  {
    label: "SNo",
    field: "S.No",
    icon: false,
    deleteIcon: false,
    editIcon: false,
    image: false,
    switchbtn: false,
    statusbtn: false,
  },
  {
    label: "User_Name",
    field: "User Name",
    icon: false,
    deleteIcon: false,
    editIcon: false,
    image: true,
    switchbtn: false,
    statusbtn: false,
  },
  {
    label: "Contact",
    field: "Contact",
    icon: false,
    deleteIcon: false,
    editIcon: false,
    image: false,
    switchbtn: false,
    statusbtn: false,
  },
  {
    label: "Institute_user",
    field: "Institute user",
    icon: false,
    deleteIcon: false,
    editIcon: false,
    image: false,
    switchbtn: false,
    statusbtn: false,
  },
  {
    label: "Email",
    field: "Email",
    icon: false,
    deleteIcon: false,
    editIcon: false,
    image: false,
    switchbtn: false,
    statusbtn: false,
  },
  {
    label: "Account_created_on",
    field: "Account created on",
    icon: false,
    deleteIcon: false,
    editIcon: false,
    image: false,
    switchbtn: false,
    statusbtn: false,
  },
  {
    label: "Last_Login",
    field: "Last Login",
    icon: false,
    deleteIcon: false,
    editIcon: false,
    image: false,
    switchbtn: false,
    statusbtn: false,
  },
  {
    label: "Status",
    field: "Status",
    icon: false,
    deleteIcon: false,
    editIcon: false,
    image: false,
    switchbtn: false,
    statusbtn: true,
  },
  {
    label: "Deactivate",
    field: "Deactivate",
    icon: false,
    deleteIcon: false,
    editIcon: false,
    image: false,
    switchbtn: true,
    statusbtn: false,
  },
  {
    label: "Take_Actions",
    field: "Take Actions",
    icon: true,
    deleteIcon: false,
    editIcon: true,
    image: false,
    switchbtn: false,
    statusbtn: false,
    subScrIcon: true,
  },
];

// Institute Admin
const usersTablesColumn = [
  { label: "S.No", field: "S.No", icon: false, image: false },
  { label: "User Name", field: "User Name", icon: false, image: true },
  { label: "Contact", field: "Contact", icon: false, image: false },
  {
    label: "Email",
    field: "Email",
    icon: false,
    image: false,
  },

  {
    label: "Account created on",
    field: "Account created on",
    icon: false,
    image: false,
  },
  {
    label: "Current Subscription Plan",
    field: "Current Subscription Plan",
    icon: false,
    image: false,
  },
  { label: "Status", field: "Status", icon: false, image: false },
  { label: "Deactivate", field: "Deactivate", icon: false, image: false },
  { label: "Take Actions", field: "Take Actions", icon: true, image: false },
];
